apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-admin
  labels:
    app: doctor-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-admin
  template:
    metadata:
      labels:
        app: doctor-admin
    spec:
      containers:
      - name: admin
        image: ghcr.io/shibil-basith/doctor-admin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-admin-svc
spec:
  selector:
    app: doctor-admin
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: doctor-admin-route
spec:
  to:
    kind: Service
    name: doctor-admin-svc
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
