apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-frontend
  labels:
    app: doctor-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-frontend
  template:
    metadata:
      labels:
        app: doctor-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/shibil-basith/doctor-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-frontend-svc
spec:
  selector:
    app: doctor-frontend
  ports:
  - name: http                  # named port for route
    port: 80                    # service port
    targetPort: 8080            # container port
    protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: doctor-frontend-route
spec:
  to:
    kind: Service
    name: doctor-frontend-svc
  port:
    targetPort: http            # use named port
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
