apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-frontend
  labels:
    app: doctor-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-frontend
  template:
    metadata:
      labels:
        app: doctor-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/shibil-basith/doctor-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-frontend-svc
spec:
  selector:
    app: doctor-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: doctor-frontend-route
spec:
  to:
    kind: Service
    name: doctor-frontend-svc
  port:
    targetPort: 80
